language: java
jdk: oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_script:
  - cd BugQueryServerSide/
script:
  - mvn test
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
