language: java
jdk: oraclejdk8

install: true
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - pip install --user codecov
  
script:
  - mvn test -P serverside

after_success:
  - codecov
#  - bash <(curl -s https://codecov.io/bash)