language: java
jdk: oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - pip install --user codecov
  
before_script:
  - cd BugQueryServerSide/
script:
  - mvn test
  - mvn cobertura:cobertura

after_success:
#  - codecov
  - bash <(curl -s https://codecov.io/bash)