coverage:
  precision: 2
  round: nearest
  range: "40...60"
  ignore: 
    - "BugQueryServerSide/src/main/java/com/bugquery/serverside/entities/"
    - "BugQueryPlugin/src/*"
    - "Bugquery/BugQueryServerSide/src/main/java/com/bugquery/serverside/examples/*"
